### ISSUE TITLE
Contact Brooklyn Marriott 

### ISSUE THREAD

**Issue by mikelking** [mikelking/wcnyc#6]
# Rindy contact Brooklyn Marriott to open discussion about Aug 7, 8, & 9 2015
- please include Kevin and myself on the correspondence
- if possible arranged a meeting with the three of us at the venue

**Comment by portfola** [comment]
Initial email sent 2/15. Got an out of office. Follow up sent 2/23.

**Comment by portfola** [comment]
Marriott is renovating the ballroom August and September and asks if we can do July?

**Comment by kcristiano** [comment]
Would have to move fast,  July is mostly booked with other camps.   Also no action on application.

Get a list of available July dates and then we can push with those.

**Comment by mikelking** [comment]
@portfola Can we try to setup a conference call with the Marriott or at least get some information regarding the weekends they might have available? Pushing into July would be my least favorite option but if that is what needs to happen then we will make it so.

## July 2015
- Weekend (1) 24, 25, 26
- Weekend (2) 17, 18, 19
- Weekend (3) 10, 11, 12
- Weekend (4) 3, 4, 5 [Obviously this one is probably out considering that NO one is likely to travel during Independence Day weekend]

So looking a head I wonder if there's any chance they would have something the end of Sept.

## September 2015
- Weekend (1) 25, 26, 27 
- Weekend (2) 18,19,20

Even further into the future puts us into Oct and that get's tricky as I am very potentially out of town the 9, 10 & 11th.

## October 2015
- Weekend (1) 2, 3, 4 
- Weekend (2) 16, 17, 18
- Weekend (3) 23, 24, 25

**Comment by mikelking** [comment]
Spoke with @kcristiano and the Marriott has returned with weekend of July 10th, 11th & 12th. That compresses our original timeline by 28 days and only would leave us 4 months to plan this assuming that WPF approves us by March 1st.

Thoughts?

**Comment by portfola** [comment]
July 10 is too aggressive in my opinion. Feels very rushed. The previous
weekend is July 4th and I will be out of town for a few days.

What do others think?

**Comment by 720creations** [comment]
I have mixed feelings. We have to consider holidays and others on calendar if we push it. Not opposed to it.  What would those options look like after renovations?

**Comment by 720creations** [comment]
I have mixed feelings. We have to consider holidays and others on calendar if we push it. Not opposed to it.  What would those options look like after renovations?

**Comment by mikelking** [comment]
It's my understanding that Oct puts us in WC US/SF territory, which makes things extremely delicate. I think if we would need to know from the Marriott if the first weekend in Oct (2,3,4) is available and then we'd need to feel out the WPF to see when WC US/SF is likely to happen. And know that if it's close we're likely to loose out on travelers.
